### ISSUE TITLE
No examples of DDS Tunneling

### ISSUE THREAD

**Issue by ctefer** [eProsima/Integration-Service-docs#22]
One of the typical scenarios described is: Communication between DDS systems located in different geographical regions through the Internet. This seems to indicate the ability to bridge two different DDS domains with each other using TCP communication. The older "Fast-RTPS Integration Service" provided a very clear shapes demo example that showed this support.

Based on the current documentation and the examples provided, I was unable to perform the same functionality as the "Fast-RTPS Integration Service" using SOSS-DDS. I have to make some assumptions about topic types and routes that seemed uncomfortable and I was never really able to get working. 

I'm not really sure why the Fast-RTPS Integration Service and the SOSS Integration Service are both called Integration Service with the same documentation template when they are clearly not the same. I was very thankful that the Fast-RTPS IS still existed.

It seems to me that SOSS-DDS should be updated for eProsima 2+ and an example of how to use TCP tunneling using the shapes demo should be provided rather than the Ros2 to DDS that is available.

Thanks

**Comment by jamoralp** [comment]
Good morning, you can find an example on this topic here: https://integration-service.docs.eprosima.com/en/latest/examples/wan_communication/wan_tcp_dds.html

Regarding the usage of DDS shapesdemo instead of ROS 2, you should just use two DDS systems in your YAML file, defining the corresponding topics and types there. You can find more information on how to write YAML configuration files for Integration Service [here](https://integration-service.docs.eprosima.com/en/latest/user_manual/yaml_config.html).

We know this has been a little bit messy, regarding the process of updating the whole product and its documentation, but everything should be fine now and the documentation has been recently updated as well. Please reopen this issue if you have any more doubts.

Thanks and sorry for the delay
